This is the Update file for the heroes table. All you need to do is run all cells to update the table and hero-pages folder to include the most recent data from Fire Emblem Heroes.

In [5]:
import pandas as pd
import bs4
import requests
import plotly.express as px
import kaleido
import regex
import time
import os
import lxml
import httpx

In [3]:
heroes_table = pd.read_csv('heroes_table.csv').drop(columns=['Unnamed: 0'])

In [ ]:
heroes = requests.get('https://feheroes.fandom.com/wiki/Level_40_stats_table')

In [ ]:
heroes = bs4.BeautifulSoup(heroes.text)

In [ ]:
rows = heroes.find_all('tr', attrs={'class':'hero-filter-element'})
# Gets all rows of Heroes as a list

In [ ]:
links = [] # This cell creates the links for each individual heroes' info pages
for i in range(len(rows)):
    links.append("https://feheroes.fandom.com" + rows[i].find_all('a')[0].get('href'))
links

In [ ]:
heroes_table = pd.DataFrame(columns=['Hero', 'Entry', 'Move', 'Weapon', 'HP', 'Atk', 'Spd', 'Def', 'Res', 'Total'])
for i in range(len(rows)):
    row = rows[i].find_all('td')
    heroes_table.loc[len(heroes_table)] = [
        row[0].find('a').get('title'),
        row[2].find('img').get('alt'),
        row[3].find('img').get('alt'),
        row[4].find('img').get('alt'),
        int(row[5].text),
        int(row[6].text),
        int(row[7].text),
        int(row[8].text),
        int(row[9].text),
        int(row[10].text)
    ]
heroes_table['Link'] = links
heroes_table # This heroes table only includes data that is available on the Lv. 40 Stats Table on the Fandom page

In [ ]:
def color(str):
    return str.split(' ')[0]

heroes_table['Color'] = heroes_table['Weapon'].apply(color)
heroes_table.head()
# This bit just adds the color of the unit by pulling from the Weapon column

Next is adding book information by pulling data from hero pages stored in the hero-pages directory.

In [18]:
test = bs4.BeautifulSoup(requests.get(heroes_table['Link'].iloc[1]).text)
float(test.find('table', attrs={'class':'wikitable hero-infobox'}).find_all('a')[-1].text)
# Test is here to find where book info is stored.

5.9

In [48]:
pagedir = os.listdir('hero-pages') # Current hero pages in hero-pages directory
pagedir[:10]
with open('hero-pages/AbelThePanther.html', 'r', encoding="UTF-8") as f:
    soup = bs4.BeautifulSoup(f, 'lxml')
    print(float(soup.find('table', attrs={'class':'wikitable hero-infobox'}).find_all('a')[-1].text))

1.0

In [5]:
versions = []
for i in range(heroes_table.shape[0]):
    temp = heroes_table['Hero'].iloc[i].split()
    for j in range(len(temp)):
        temp[j] = temp[j].strip(':"')
        name = ''.join(temp)

    with open(f'hero-pages/{name}.html', 'r', encoding="UTF-8") as f:
        soup = bs4.BeautifulSoup(f.read(), 'lxml')
        versions.append(float(soup.find('table', attrs={'class':'wikitable hero-infobox'}).find_all('a')[-1].text))
    
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299

In [6]:
# Add column
heroes_table['Version'] = versions
heroes_table.head()

,Hero,Entry,Move,Weapon,HP,Atk,Spd,Def,Res,Total,Link,Color,Version,Book
0,Abel: The Panther,Shadow Dragon / (New) Mystery,Cavalry,Blue Lance,39,33,32,25,25,154,https://feheroes.fandom.com/wiki/Abel:_The_Pan...,Blue,1.0,1
1,Aelfric: Custodian Monk,Three Houses,Infantry,Red Tome,43,40,31,20,37,171,https://feheroes.fandom.com/wiki/Aelfric:_Cust...,Red,5.9,5
2,Alcryst: Tender Archer,Engage,Infantry,Colorless Bow,39,43,46,30,24,182,https://feheroes.fandom.com/wiki/Alcryst:_Tend...,Colorless,7.7,7
3,Alcryst: Tender Groom,Engage,Infantry,Red Bow,40,44,46,35,23,188,https://feheroes.fandom.com/wiki/Alcryst:_Tend...,Red,8.5,8
4,Alear: Awoken Divinity,Engage,Infantry,Green Breath,40,41,47,33,37,198,https://feheroes.fandom.com/wiki/Alear:_Awoken...,Green,7.8,7

In [7]:
# Now use that Version column to create a Book column
def book(ver):
    return int(ver)

heroes_table['Book'] = heroes_table['Version'].apply(book)
heroes_table.tail()

,Hero,Entry,Move,Weapon,HP,Atk,Spd,Def,Res,Total,Link,Color,Version,Book
1295,Zephia: Scheming Dragon,Engage,Flying,Red Tome,41,40,44,23,24,172,https://feheroes.fandom.com/wiki/Zephia:_Schem...,Red,7.70,7
1296,Zephiel: The Liberator,The Binding Blade,Armored,Red Sword,55,35,16,38,24,168,https://feheroes.fandom.com/wiki/Zephiel:_The_...,Red,1.20,1
1297,Zephiel: Winter's Crown,The Blazing Blade,Armored,Red Sword,48,38,19,38,36,179,https://feheroes.fandom.com/wiki/Zephiel:_Wint...,Red,4.00,4
1298,Zihark: Ninja Blademaster,Path of Radiance,Infantry,Red Sword,43,37,42,30,24,176,https://feheroes.fandom.com/wiki/Zihark:_Ninja...,Red,4.11,4
1299,Þjazi: Ruthless Jötun,Heroes,Armored,Green Axe,49,50,18,47,42,206,https://feheroes.fandom.com/wiki/%C3%9Ejazi:_R...,Green,8.11,8

In [ ]:
# 47m 3.2s runtime

# def version(link):
#     time.sleep(0.5)
#     html = bs4.BeautifulSoup(requests.get(link).text)
#     return float(html.find('table', attrs={'class':'wikitable hero-infobox'}).find_all('a')[-1].text)

# heroes_table['Version'] = heroes_table['Link']
# heroes_table['Version'] = heroes_table['Version'].apply(version)

# Obsolete code. Very inefficient way to pull version info for each unit for Version Column

In [ ]:
# heroes_pages = heroes_table[['Hero', 'Link']]
# heroes_pages.head()
# Hero and Link table

In [ ]:
# runtime 50m 5.8s

# def grabber(link):
#     time.sleep(0.5)
#     print(link.split('/')[-1])
#     return bs4.BeautifulSoup(requests.get(link).text)

# heroes_pages['Pages'] = heroes_pages['Link'].apply(grabber)

# Another obsolete bit of code that essentially adds the entire HTML page of each hero in a Page column.

In [11]:
test = bs4.BeautifulSoup(requests.get(heroes_table['Link'].iloc[0]).text)
test.find('time').text
# Test is here to find where date added is stored.

'2017-02-02'

In [19]:
releaseDate = []
for i in range(heroes_table.shape[0]):
    temp = heroes_table['Hero'].iloc[i].split()
    for j in range(len(temp)):
        temp[j] = temp[j].strip(':"')
        name = ''.join(temp)

    with open(f'hero-pages/{name}.html', 'r', encoding="UTF-8") as f:
        soup = bs4.BeautifulSoup(f.read(), 'lxml')
        releaseDate.append(soup.find('time').text.strip())
    
    print(name)

AbelThePanther
AelfricCustodianMonk
AlcrystTenderArcher
AlcrystTenderGroom
AlearAwokenDivinity
AlearDragonChild
AlearDragonYouth
AlearEngagingFire
AlearFellDragonChild
AlearGiftedDragons
AlearRedDaysPast
AlearSeasideDragon
AlfonseAskranDuo
AlfonseHeirtoOpenness
AlfonsePrinceofAskr
AlfonseSpringPrince
AlfonseUpliftingLove
AlfredFloralProtector
AlmHeroofProphecy
AlmImperialAscent
AlmLovebirdDuo
AlmPowerfulResolve
AlmSaint-King
AltenaLuminousRider
AltinaCross-TimeDuo
AltinaDawn'sTrueblade
AltinaUnrivaledDawn
AmeliaBlossomingTalent
AmeliaRoseoftheWar
AnankosSeethingSilence
AnnaCommander
AnnaSecretCharmer
AnnaSecretSeller
AnnaTwicetheAnna
AnnaWealth-Wisher
AnnandKnight-Defender
AnnetteFestiveHelper
AnnetteOverachiever
ArdenStrongandTough
AresBlackKnight
AreteRequiem'sBeauty
ArionGungnir'sHeir
ArlenMageofKhadein
ArthurFuriousMage
ArthurHaplessHero
ArturSilverSaint
ArvalCycleKeeper
ArvisEmperorofFlame
AsbelWindsweptYouth
AshBorrowedPower
AshEarnestGreetings
AshRetainertoAskr
AsheBuddingChivalry
AsheChivalricAmends
AsheFabledSeaKnight
AsheraOrderGoddess
AshnardMadKing
AskrGodofOpenness
AskrOpenHarvest
AskrRenewedGods
AstramMidia'sHero
AstridResoluteDamsel
AthenaBorderlandSword
AthosOmniscientOne
AtlasForestMuscle
AugustAstuteTactician
AversaDarkOne
AyraAstra'sWielder
AyraSupremeAstra
AyraTogetherinTea
AzamaCarefreeMonk
AzelleYouthfulFlame
AzuraCelebratorySpirit
AzuraHatariDuet
AzuraLadyofBallads
AzuraLadyoftheLake
AzuraSong'sReflection
AzuraValliteSongstress
AzuraYoungSongstress
BaldrCelestialSunGod
BaldrRaysofJudgment
BalthusKingofGrappling
BalthusSummer'sBigBet
BantuTiki'sGuardian
BarstTheHatchet
BartreEarsomeWarrior
BartreFearlessWarrior
BasilioFeroxiWest-Khan
BastianCrimea'sKeystone
BennySensitiveSoul
BerkutDebonairNoble
BerkutPridefulPrince
BerkutPurgatorialPrince
BernadettaEternalLoner
BernadettaFrostyShut-In
BernadettaLateHibernator
BernadettaShelteredLoner
BertramDreadCavalier
BerukaQuietAssassin
BlackKnightMortalLegend
BlackKnightSinisterGeneral
BlackKnightTheNight'sBlade
BoeySkillfulSurvivor
BorsOstia'sBastion
BoydFutureGreat
BradyDauntingPriest
BramimondTheEnigma
BrigandBossKnownCriminal
BrigidAwakenedBow
BrigidOrgahilPirate
BrunnyaDevotedGeneral
BrunoMaskedHare
BrunoMaskedKnight
BrunoMaskedReveler
BylethAnchorofHope
BylethFellStar'sDuo
BylethFountofLearning
BylethFrostyProfessors
BylethProvenProfessor
BylethSublimeLight
BylethTestedProfessor
BylethTheFódlanLight
BylethTheFódlanStar
BylethVengeanceVessel
CaedaBelovedQueen
CaedaMarth'sFaithful
CaedaPrincessofTalys
CaedaSea-BlossomPair
CaedaTalys'sBride
CaedaTalys'sHeart
CaeldoriPerfectAngel
CaellachTigerEye
CainTheBull
CaineghisGallia'sLionKing
CamillaAlluringDarkness
CamillaBewitchingBeauty
CamillaFlowerofFantasy
CamillaHolidayTraveler
CamillaLightofNohr
CamillaMidnightBloom
CamillaSpringPrincess
CamillaSteamySecrets
CamillaTropicalBeauty
CamillaYoungBeauty
CamusSableKnight
CanasWisdomSeeker
CandaceSlySnatcher
CasparHotheadedInciter
CasparSummerIntensity
CastorLovingSon
CathCaperCaptain
CathMasterThief
CatherineThunderKnight
CatriaAzureWingPair
CatriaMiddleWhitewing
CatriaMildMiddleSister
CatriaSpringWhitewing
CatriaWindsweptKnight
CeciliaEtrurianBride
CeciliaEtrurianGeneral
CeciliaFestiveInstructor
CedHeroontheWind
CedSageoftheWind
CelicaCaringPrincess
CelicaImprisonedSoul
CelicaOfEchoes
CelicaQueenofValentia
CelicaSunlitPriestesses
CelicaValentia'sHope
CelicaWarriorPriestess
CélineBlissfulTeaParty
CélineJoyousRoyal
CélineTeatimeNinja
CervantesInvincibleGeneral
ChadLycianWildcat
CharlotteMoneyMaiden
CharlotteWilyWarrior
ChercheShadedbyWings
ChercheWyvernFriend
ChloéFairy-TaleFlier
ChloéSpringWings
ChromCrownedExalt
ChromExaltedPrince
ChromFate-DefyingDuo
ChromFatedHonor
ChromFellExalt
ChromGiftedLeader
ChromKnightExalt
ChromPivotalBlow
ChromSpringExalt
ChulainnLeadingGladiator
ChulainnUnbeatenWarrior
CitrinneCaringNoble
ClairHighbornFlier
ClanneSummerFan
ClarineRefinedNoble
ClarisseSniperintheDark
ClaudeAlmyra'sKing
ClaudeDistantDeer
ClaudeGoldenBreeze
ClaudeKingofUnification
ClaudeTheSchemer
ClaudeTropicalTrouble
ClaudeYuletideSchemer
CliveIdealisticKnight
ColmCapableThief
ConradMaskedKnight
ConradUnmaskedKnight
ConstanceFallenNoble
CordeliaKnightParadise
CordeliaKnightParagon
CordeliaPerfectBride
CordeliaUnyieldingSnow
CormagAloofLanceman
CorneliaSaintConsumed
CorrinBloodboundBeast
CorrinCelestialSorcerer
CorrinChildofDawn
CorrinChildofDusk
CorrinDaylightNinjaAct
CorrinDreamPrince
CorrinDreamPrincess
CorrinEnjoyingTradition
CorrinFatefulPrince
CorrinFatefulPrincess
CorrinNightfallNinjaAct
CorrinNoviceVacationer
CorrinOfFates
CorrinSilentBloodline
CorrinStarrySeer
CorrinWailingSoul
CorrinYoungKinship
CynthiaHeroChaser
CyrilRhea'sAttendant
DagdarReformedBandit
DagrBlusterPrincess
DagrNewYearJötnar
DagrSun'sRadiance
DagrSunnyBloom
DarrosSeawalker
DeathKnightTheReaper
DedueDauntlessBeast
DedueDimitri'sVassal
DedueLoyalLifeGuard
DeenBladedSandstorm
DeirdreFatedSaint
DeirdreLadyoftheForest
DeltheaFreeSpirit
DeltheaProdigyinBloom
DeltheaTatarrah'sPuppet
DewBenevolentThief
DheginseaHarvestGoldoan
DiamantFortifiedKing
DiamantGallantNinja
DiamantRisingPower
DieckWoundedTiger
DimitriBlessedProtector
DimitriKingofFaerghus
DimitriSavageBoar
DimitriSaviorKing
DimitriSky-BlueLion
DimitriStargazingLion
DimitriTheProtector
DíthorbaCuttingKnight
DonnelSunnyVillager
DonnelVillageHero
DorcasPumpkinSmasher
DorcasSereneWarrior
DorotheaDaringEx-Singer
DorotheaSolarSongstress
DorotheaTwilitHarmony
DorotheaYuletideDancer
DorothyDevotedArcher
DozlaHarvestAttendant
DraugGentleGiant
DuesselObsidian
DumaGodofStrength
DumaStrengthandLove
DwyerSleepyButler
EchidnaUnyieldingIdealist
EdainLadyofYngvi
EdelgardAdornedEagle
EdelgardAdrestianEmperor
EdelgardFlameEmperor
EdelgardHegemonHusk
EdelgardSnowfallFuture
EdelgardSunEmpresses
EdelgardTheFuture
EdwardBladeofJustice
EffieArmyofOne
EffieDedicatedHeart
EikþyrnirBlessedStrength
EikþyrnirFitforWaves
EikþyrnirQuietingStrength
EikþyrnirResolvedtoTrain
EirLifeAscendant
EirMercifulDeath
EirRenewedLife
EirikaAnamnesisLady
EirikaBeachRestorer
EirikaGentleasSnow
EirikaGracefulResolve
EirikaOftheSacred
EirikaPledgedRestorer
EirikaResolutePrincess
EirikaRestorationLady
EirikaTwinRefulgence
EitrHandofNothing
EitrSpringSunrise
EitriYouthfulSage
EldiganLionheart
EldiganStruttingLion
EleonoraShootingStarlet
ElffinTruthBeholden
EliceAlteanPrincess
ElimineScouringSaint
ElinciaDevotedQueen
ElinciaEstivalPrincess
ElinciaLostPrincess
ElinciaSeasideQueen
ElinciaUndauntedQueen
EliseBubblingFlower
EliseBuddingFlower
EliseSparklingSmile
EliseSweetheartRoyals
EliseTropicalFlower
EliwoodBlazingKnight
EliwoodDevotedLove
EliwoodKnightofLycia
EliwoodMarquessPherae
EliwoodPledgedFriend
ElmResoluteGrouch
ElmRetainertoEmbla
EmblaClosed-OffBride
EmblaGodofClosure
EmmerynGentleExalt
EmmerynSelflessExalt
EnaAutumnTactician
EphraimArdentPrince
EphraimDynasticDuo
EphraimLegendaryLord
EphraimRestorationLord
EphraimSacredTwinLord
EphraimSparklingGallantly
EphraimSunshineValiant
EremiyaBishopofWoe
ErinysEarnestKnight
ErkStudiousMage
EstJuniorWhitewing
EstSpringtimeFlier
EstSweetBabySis
EthlynGlimmeringLady
EthlynSpiritedPrincess
EtieFitnessFighter
EwanEagerStudent
ExcellusConqueror’sWile
EyvelMistressofFiana
FaeChildlikeDragon
FaeDivineDragon
FaeHolidayDear
FáfnirFreshAmbition
FáfnirKingofDesolation
FargusBadonBuccaneer
FarinaTheGreatWing
FayeDevotedHeart
FayeDrawnHeartstring
FebailMercenaryWaif
FeeAspiringKnight
FeliciaConfidentlyCold
FeliciaMaidMayhem
FeliciaOfftheMenu
FelixIcyGiftGiver
FelixLone-WolfBlade
FelixSavant'sService
FelixSwordSavant
FerdinandHighbornSipper
FerdinandNoblestofNobles
FernandTraitorousKnight
FinnDevotedService
FinnLanceofLegend
FioraAirborneWarrior
FioraDefrostedIlian
FirDualWarriors
FirStudentofSpring
FirSwordStudent
FirSwordmaiden
FjormBrideofRime
FjormGleamingIcePair
FjormIceAscendant
FjormNewTraditions
FjormPrincessofIce
FjormSeasideThaw
FlameEmperorBringerofWar
FlaviaBoldBride
FlaviaFeroxiEast-Khan
FlaynPlayingInnocent
FlaynSillyKitty-Cat
FloraColdasIce
FloraPolar-Perfect
FloraSignatureDish
FlorinaAzure-SkyKnight
FlorinaLovelyFlier
FogadoAffablePrince
FogadoSummerofBliss
FomortiisDarkofNight
FomortiisDemonKing
FordeUnfetteredKnight
ForrestFashionForward
ForsythLoyalLieutenant
FrammeSpringFangirl
FrederickHorizonWatcher
FrederickPoliteKnight
FrederickYouthinService
FreyjaFleetingSummer
FreyjaLadyofNightmare
FreyjaParallelHearts
FreyrDream-King
FreyrEstivalDreams
FugaForceofGales
GaiusCandyStealer
GaiusThiefExposed
GalleAzureRider
GalzusDarkBladeofOd
GanglötDeathAnew
GangrelPlegia'sMadKing
GaronKingofNohr
GatekeeperNothingtoReport
GatrieArmoredAmour
GeeseALifeatSea
GennyDressedwithCare
GennyEndearingAlly
GeoffreyRealm'sProtector
GerikDesertTiger
GeromeMaskedRider
GharnefDarkPontifex
GilliamWallofSilence
GinnungagapRulerofNihility
GlenSunstone
GoldmaryCoyBeachDivas
GonzalezKindlyBandit
GordinAlteanArcher
GotohApostleofNaga
GotohWhiteSage
GrayWryComrade
GregorSwellSword
GreilHeroicExemplar
GrimaTyrantofDespair
GrimaTyrantofRuin
GrissIndulgingPain
GuiniverePrincessofBern
GuinivereQueenofBern
GullveigGlitteringSunlight
GullveigGoldenSeer
GullveigSeerBeyondTime
GunnthráBeamingSmile
GunnthráVoiceofDreams
GunnthráYear'sFirstDream
GunterInveterateSoldier
GustavMajesticLove
GustavSovereignSlain
GuyKutolahBlade
GwendolynAdorableKnight
HaarBlackTempest
HaarTempestRunner
HaitakaPersistentGeneral
HanaFocusedNinja
HanaFocusedSamurai
HanaStrivingHeart
HansAmbitiousBrute
HapiDrawn-OutSigh
HapiEternalSunlitPair
HardinDarkEmperor
HardinTheCoyote
HarkenTroubledWarrior
HawkeyeDesertGuardian
HawkeyeTaciturnGuardian
HayatoDivinerofReppu
HeathWanderingKnight
HeathWyvernNinja
HeatherWanderingNinja
HectorBraveWarrior
HectorDressed-UpDuo
HectorGeneralofOstia
HectorJustHeretoFight
HectorMarquessofOstia
HectorSteelWarrior
HectorSwornFriend
HeiðrInnocentGoddess
HeiðrúnHealingNectar
HeiðrúnPeacefulHorizon
HeiðrúnSistersofHealing
HelDeathSovereign
HelbindiSavageScourge
HelbindiSeasideScourge
HenrietteOverflowingLove
HenryHappyVampire
HenryPeculiarEgg
HenryTwistedMind
HestiaDuma'sWitch
HildaDeer'sTwo-Piece
HildaHelpingHand
HildaHolidayLayabout
HildaIdleMaiden
HildaQueenofFriege
HinataSamuraiGroom
HinataWildSamurai
HinokaBlueSkyWarrior
HinokaFairPiratePair
HinokaRelaxedWarrior
HinokaThunderingWings
HinokaWarriorofGusto
HinokaWarriorPrincess
HöðrDuskShadowGod
HolstHeroofLeicester
HomerTravelingBard
HortensiaLittleCharmer
HortensiaWinter'sDearest
HræsvelgrQuietingBlade
HræsvelgrWingsofHealing
HrídIcyBlade
HrídIslandIcePrince
HrídResolutePrince
HubertCrimsonSchemer
HubertSinisterServant
HughWorldlyMage
IagoNohr'sTactician
IdunnDarkPriestess
IdunnDivineDemon
IdunnDragonkinDuo
IgnatzSnowscapeArtist
IgreneNabataProtector
IgreneNinjaofNabata
IgreneSwornProtectors
IkeBraveMercenary
IkeClose-KnitSiblings
IkeDesertMercenary
IkeOfRadiance
IkeStalwartHeart
IkeVanguardLegend
IkeYoungMercenary
IkeZealUnleashed
IlyanaAwakenedAppetite
IlyanaHungeringMage
IlyanaTreatHarvester
IngridBeaconofHonor
IngridCordialTeatime
IngridGalatea'sHeir
IngridSolsticeKnight
InigoFestivalFlower
InigoFlowerPicker
InigoIndigoDancer
InnesFlawlessForm
InnesFrelianMoonlight
InnesNewYear'sAim
InnesRegalStrategician
IsadoraEscortofPherae
IshtarEchoingThunder
IshtarThunderGoddess
IshtarThunder'sWaltz
ItsukiFindingaPath
IvySnowQueen
IvyTidalBreeze
JaffarAngelofDeath
JaffarAngelofNight
JagenVeteranKnight
JakobDevotedMonster
JakobDevotedServant
JamkePrinceofVerdane
JarodNevassaGeneral
JedahPriestofDuma
JeorgePerfectShot
JeraltBladeBreaker
JesseBlitheMercenary
JillFieryDracoknight
JorgeTravelingPeddler
JoshuaResoluteTempest
JoshuaTempestKing
JoshuaTropicalGambler
JuliaBridesofLight
JuliaCrusaderofLight
JuliaHeartUsurped
JuliaNaga'sBlood
JuliaScionoftheSaint
JulianTenderThief
JuliusScionofDarkness
JunoNimbleGrace
JunoSoaringBride
KadenKitsuneBraggart
KadenRefreshedKitsune
KageroBeverageNinja
KageroBondUnwavering
KageroHonorableNinja
KageroSpringNinja
KagetsuOnigiriSamurai
KamuiWanderingBlade
KanaDragonPrincess
KanaDragonSpawn
KanaRisingDragon
KanaRisingSunlight
KarelSwordDemon
KarinDrivenKnight
KarlaSpringReveries
KarlaSun-PiercingSteel
KarlaSwordVassal
KatarinaTorchlitWanderer
KatarinaWaywardOne
KazeEasygoingNinja
KeatonLupineCollector
KeatonResolvedWolfskin
KellamPumpkinKnight
KempfConnivingGeneral
KentCrimsonShield
KiragiUpbeatArcher
KiriaCoolFaçade
KjelleFairFighter
KleinSilverNobleman
KliffCuriousSpirit
KnollDarknessWatcher
KrisArdentFirebrand
KrisUnknownHero
KrisUnsungHero
KronyaGleamingBlade
KurthnagaAutumnGoldoan
KvasirSeerofthePast
KvasirUnknownFuture
KyleZealousKnight
KyzaTigerofFortune
L'ArachelHarvestPrincess
L'ArachelPrincessofLight
L'ArachelSeekerofJustice
L'ArachelSummerPrincess
LachesisBallroomBloom
LachesisLionheart'sSister
LaegjarnBurningSun
LaegjarnFlameandFrost
LaegjarnFlameAscendant
LaegjarnNewExperiences
LaegjarnSheathedSteel
LaevateinBonfire'sBlaze
LaevateinKumadeWarrior
LaevateinNinjaofMúspell
LaevateinSearingSteel
LanaBenevolentBride
LapisForageroftheSea
LapisMightyBride
LapisMightyFlower
LaraStepLively
LarceiBrideofAstra
LarceiKeenKin
LarceiScionofAstra
LarumDancingBride
LarumSprightlyDancer
LaslowDancingDuelist
LaurentTheElucidator
LæraðrQuietingHeart
LeanneForest'sSong
LegaultTheHurricane
LegionMaskedManiac
LeifDestinedScions
LeifPrinceofLeonster
LeifSworntoCountry
LeifUnifierofThracia
LeilaKeenLookout
LeilaRoseamidFangs
LeilaSuperbShadow
LenaBereftAngel
LenaTenderAngel
LeneYearningDancer
LeoDarkSprout
LeoExtraTomatoes
LeoFestivalBonds
LeoSeashore'sPrince
LeoShroudedHeart
LeoSorcerousPrince
LeonTrueofHeart
LeonardoFreedom'sArrow
LeonieRelentlessRays
LetheCatAttack
LetheGallia'sValkyrie
LetheNewYear'sClaw
LetiziaCurseDirector
LewynGuidingBreeze
LewynWind-SongScion
LexYoungBlade
LibraFetchingFriar
LífArcaneBlade
LífLethalSwordsman
LífUndyingTiesDuo
LifisTerrorofIz
LilinaBeachsideBloom
LilinaBeamingBride
LilinaBlushofYouth
LilinaBrilliantFlame
LilinaDelightfulNoble
LilinaFirelightLeader
LilithAstralDaughter
LilithSilentBroodling
LimstellaLivingConstruct
LindeBoundbyFate
LindeLightMage
LindeSummerRays
LinhardtHevring'sHeir
LinhardtSpringSnoozer
LinoanLadyofTarrah
LinusMadDog
LinusSavageDog
LissaLittlestPrincess
LissaPureJoy
LissaSprightlyCleric
LissaSweetCelebrant
LloydVengefulWolf
LloydWhiteWolf
LokiSpringTrickster
LokiTheTrickster
LokiTricksterGod
Lon'quSolitaryBlade
Lon'quSpringJitters
LorenzHighbornHeat
LouiseEternalDevotion
LouiseLadyofViolets
LuciaLoyaltyEnrobed
LuciaTirelessAdvisor
LucinaBravePrincess
LucinaFate'sResolve
LucinaFutureFondness
LucinaFutureWitness
LucinaGloriousArcher
LucinaShadowsofFate
LucinaSpringExalt
LuciusCalmingLight
LuciusTheLight
LudveckRebelliousDuke
LughAnimaChild
LukasBuffetforOne
LukasSharpSoldier
LukeRowdySquire
LumeraCorruptedDragon
LumeraDragonMonarch
LumeraInDistantSkies
LuteProdigy
LuteSummerProdigy
LuthierOddWayfarer
LuthierSpringHopes
LynBlazingWhirlwind
LynBraveLady
LynBrideofthePlains
LynLadyoftheBeach
LynLadyofthePlains
LynLadyoftheWind
LynNinja-FriendDuo
LynOfBlazing
LynPlainsWind
LynWind'sEmbrace
LyonDemonKing
LyonEsteemedRoyals
LyonGrado'sGaze
LyonShadowPrince
LyonSunlitPrince
LyreLapCatofLuxury
LysitheaChildProdigy
LysitheaEarnestSeeker
LysitheaGiftedStudents
LysitheaTeaSweetener
MachyuaBladeofGales
MaeBundleofEnergy
MaeSpringCheer
MaliceBloomingBlade
MaliceDeftSellsword
MamoriMicrowavin'Idol
ManuelaSilverCaroler
MarciaPetulantKnight
MareetaAstraAwakened
MareetaSwordofStars
MareetaTheBlade'sPawn
MariaMinerva'sSister
MariaRitualSacrifice
MariaSunnySmile
MarianneAdoptedDaughter
MarianneCursedBlessing
MarianneSereneAdherent
MaribelleDireDamsel
MarisaCrimsonFlash
MarisaCrimsonRabbit
MarisaWillfulBlades
MarkWindsofHope
MarlaDuma'sWitch
MarniPiningforPraise
MarthAlteanGroom
MarthAlteanPrince
MarthEnigmaticBlade
MarthHero-King
MarthLegaciedHero
MarthLoveandCourage
MarthMaskedGladiator
MarthOfBeginnings
MarthPrinceofLight
MarthRoyalAlteanDuo
MathildaLegendaryKnight
MatthewFaithfulSpy
MatthisBrothertoLena
MauvierPenitentKnight
MedeusEarth-DragonKing
MedeusLastEarthDragon
MeladyCrimsonRider
MelíaiWarriorWanderer
MercedesKindlyDevotee
MercedesUnfussedBasker
MerlinusPherae'sClerk
MerricChangingWinds
MerricWindMage
MerricWindPontifex
MerrinSuaveKnight
MetodeyShrewdBraggart
MiaBuddingBlade
MiaHarmonicBlades
MiaLadyofBlades
MiaMoonlitWitch
MiaSummerSlice
MicaiahDawnWind'sDuo
MicaiahDawningMaiden
MicaiahOfDawn
MicaiahPriestessofDawn
MicaiahQueenofDawn
MicaiahRadiantQueen
MicaiahSummer'sDawn
MicaiahWavecrestMaiden
MichalisAmbitiousKing
MichalisFruitingAmbition
MidirArcherofYngvi
MidoriReliableChemist
MikotoCaringMother
MilaGoddessofLove
MinervaPrincess-Knight
MinervaRedDragoon
MinervaVerdantDragoon
MirabilisDaydream
MirabilisSpringDaydream
MirabilisSugarplumVision
MirandaWillfulPrincess
MirielRapierIntellect
MistHelpfulSister
MistPurestSpirit
MonicaFavoredVassal
MordecaiGentleFiretender
MordecaiKindheartedTiger
MorganDevotedDarkness
MorganFatedDarkness
MorganLadfromAfar
MorganLassfromAfar
MozuTragicStart
MuarimRawInstinct
MurdockLoyalGeneral
MúspellFlameGod
MúspellRagingInferno
MustafaPlegianChampion
MycenZofia'sChampion
MyrrhAdoredDragon
MyrrhGreatDragon
MyrrhGuardianDragon
MyrrhSpookyMonster
MyrrhSpringHarmony
NaesalaSea'sShadow
NaesalaSky'sShadow
NagaDragonDivinity
NagaHarvestDivinity
NagaRulerofDragons
NagiDragonAvatar
NagiHopefulEternity
NahGratefulOne
NahLittleMiss
NailahBlessedQueen
NailahHatariScorcher
NailahUnflinchingEye
NannaBelovedPrincess
NannaMystletainnScion
NannaNordionPrincess
NarcianVernalGeneral
NarcianWyvernGeneral
NatashaSacredHealer
NavarreScarletNinja
NavarreScarletSword
NeimiTearfulArcher
NelStoicBride
NelStoicDragon
NemesisKingofLiberation
NepheneeFestivalHarmony
NepheneeFierceHalberdier
NepheneeSincereDancer
NergalTraitortoNabata
NerþuzBeachChaperone
NerþuzDivineAbundance
NerþuzGodoftheLand
NerþuzNew-YearDoter
NiðavellirFoundingKing
NíðhöggrDazeofHealing
NíðhöggrQuietingDose
NiflGodofIce
NiflTropicalIceGod
NiimeMountainHermit
NilesCrueltoBeKind
NilesForbiddenTease
NilsBrightBard
NilsSnowflakeMelody
NilsWanderingStar
NinaEyeSpy
NinaShadowyFigures
NinianBright-EyedBride
NinianFrozenHeart
NinianIce-DragonOracle
NinianOracleofDestiny
NinoBurstofSummer
NinoFang'sHeart
NinoFlowerofFrost
NinoPaleFlower
NinoPiousMage
NinoSpiritedSorcerer
NoahMercenary-Errant
NoireDemurelyDeft
NoireOfTwoMinds
NoireShadeSeeker
NomahPriestofMila
NorneSeasideVolunteer
NorneTheVolunteer
NóttMoon'sElegance
NowiEternalWitch
NowiEternalYouth
NuibabaMistressofFear
NynaTheLastPrincess
NyxRulebreakerMage
OboroFierceBride-to-Be
OboroFierceFighter
OdinPotentForce
OgierOstia'sNewBlade
OgmaBladeonLeave
OgmaFormerGladiator
OgmaLoyalBlade
OliverAdmirerofBeauty
OliviaBlushingBeauty
OliviaFestivalDancer
OliviaSky-HighDancer
OliviaWavecrestDancer
OlwenBlueMageKnight
OlwenRighteousKnight
OpheliaDramaticHeroine
OpheliaStarlitMaiden
OrochiMerryDiviner
OrsonPassion'sFolly
OscarAgileHorseman
OsianScoldedSoldier
OswinImpregnableKnight
ÓtrKingsbrother
OwainChosenOne
OwainDevotedDefender
PallaEldestBun-Bun
PallaEldestWhitewing
PallaKindEldestSister
PallaSisterlyTrio
PallaSoaringSummer
PandreoPartyPriest
PanetteClassyBrawler
PanneProudTaguel
PanneWelcomingDawn
PattyYouthfulThief
PelleasAshnard'sOrphan
PentFancyFiancé
PentMageGeneral
PeonyÁlfarDreamDuo
PeonyCherishedDream
PeonyFruitfulDream
PeonySweetDream
PercevalKnightlyIdeal
PeriPlayfulSlayer
PerneDacianScoundrel
PetraFarawaySun
PetraPrincessofBrigid
PetrineIcyFlame-Lancer
PhilaPegasusMaster
PhinaRovingDancer
PlumeriaLewdDream
PlumeriaRapturousDream
PlumeriaSpringDance
PlumeriaTemptationAnew
PriamRadiantHero
PriscillaDelicatePrincess
PythonApatheticArcher
QuanLightfootPrince
QuanLuminousLancer
RafalAtoningDragon
RafielBlessedWings
RaighDarkChild
RanulfConsiderateGaze
RanulfFriendofNations
RaphaelMuscle-Monger
RatatoskrMendingHand
RathWolfofSacae
RavenPeerlessFighter
RebeccaBreezyScamp
RebeccaWildflower
ReginnBearingDawn
ReginnBearingHope
ReginnDvergrHeir
ReinaSanguineShinobi
ReinhardtLightning'sRondo
ReinhardtThrudReborn
ReinhardtThunder'sFist
ReinhardtThunder'sSword
RennacRichMerchant
ReysonWhitePrince
RhajatBlackMagician
RheaAuraofLove

In [20]:
heroes_table['ReleaseDate'] = releaseDate

In [21]:
# heroes_table = heroes_table.drop(columns=['Link'])
heroes_table.to_csv('heroes_table.csv') # I'll keep the link column in, just as a reference.

##### Below is code that essentially pulls each hero's info page as an HTML file and adds it to the hero-pages folder. This is done to keep the file size of the heroes table to a minimum, as well as keeping a local reference for each page that makes accessing these pages quicker and more efficient. The hero-pages folder is gitignored.

In [7]:
heroes_table = pd.read_csv('heroes_table.csv').drop(columns=['Unnamed: 0'])
pagedir = os.listdir('hero-pages') # Current hero pages in hero-pages directory

In [8]:
missingidx = []
for i in range(heroes_table.shape[0]):
    temp = heroes_table['Hero'].iloc[i].split()
    for j in range(len(temp)):
        temp[j] = temp[j].strip(':"')
        name = ''.join(temp)

    if f'{name}.html' not in pagedir:
        print(heroes_table['Hero'].iloc[i])
        missingidx.append(i)

# Use this to check which pages are currently not in directory

Rennac: Rich "Merchant"
Reyson: White Prince
Rhajat: Black Magician
Rhea: Aura of Love
Rhea: Immaculate One
Rhea: Loving Matriarch
Rhea: Witch of Creation
Rhys: Gentle Basker
Rickard: Carefree Culprit
Ricken: Shepherd Novice
Riev: Blood Beryl
Rinea: Reminiscent Belle
Rinkah: Consuming Flame
Rinkah: Scion of Flame
Robin: Exalt's Deliverer
Robin: Exalt's Other Half
Robin: Exalt's Right Hand
Robin: Fall Reincarnation
Robin: Fall Vessel
Robin: Fated Vessel
Robin: Fell Reincarnation
Robin: Fell Tactician
Robin: Fell Vessel
Robin: Festive Tactician
Robin: High Deliverer
Robin: Keen Groom
Robin: Mystery Tactician
Robin: Seaside Tactician
Robin: Tactful Deliverer
Robin: Vessels of Fate
Roderick: Steady Squire
Rolf: Tricky Archer
Ronan: Villager of Iz
Rosado: Adorable Artist
Roshea: Coyote's Faithful
Ross: His Father's Son
Roy: Blazing Bachelors
Roy: Blazing Lion
Roy: Brave Lion
Roy: Young Lion
Roy: Youthful Gifts
Rudolf: Emperor of Rigel
Rune: Source of Wisdom
Rutger: Lone Swordsman
Ryoma: Dancing Samurai
Ryoma: Peerless Samurai
Ryoma: Samurai at Ease
Ryoma: Supreme Samurai
Ryoma: Warrior of Bonds
Saber: Driven Mercenary
Saber: Dune Walker
Safy: Font of Piety
Saias: Bishop of Flame
Sain: Green Lance
Saizo: Angry Ninja
Saizo: Hoshido's Flame
Sakura: Gentle Nekomata
Sakura: Hot-Spring Healer
Sakura: In Full Bloom
Sakura: Loving Priestess
Saleh: Vernal Sage
Salem: Dark Sage
Sanaki: Apostle in White
Sanaki: Begnion's Apostle
Sanaki: Dawnsworn Ninja
Sara: Lady of Loptr
Saul: Loving Shepherd
Saul: Minister of Love
Say'ri: Chon'sin's Blade
Say'ri: Righteous Bride
Scarlet: Rebellious Streak
Scáthach: Astra's Wake
Seadall: Misfortune-Teller
Sedgar: Coyote's Dutiful
Seiðr: Goddess of Hope
Seiðr: Time's Goddesses
Seiros: Saint of Legend
Selena: Admiring General
Selena: Cutting Wit
Selena: Fluorspar
Selena: Sandbar Fluorspar
Seliph: Enduring Legacy
Seliph: Heir of Light
Seliph: Light's Legacy
Seliph: Scion of Light
Selkie: Free Spirit
Selkie: New Year's Spirit
Sephiran: Hoary Sovereign
Serra: Outspoken Cleric
Seteth: Seiros Adherent
Seth: Silver Knight
Seth: Silver-Sea Knight
Setsuna: Absent Archer
Severa: Bitter Blossom
Severa: Secret Dreamer
Shamir: Archer Apart
Shamir: Heartbeats United
Shamir: Lone-Moon Ninja
Shanna: Bridal Novice
Shanna: Sprightly Flier
Shannan: Wielder of Astra
Sharena: Hopeful Princess
Sharena: Pillars of Peace
Sharena: Princess of Askr
Sharena: Spring Princess
Sheena: Princess of Gra
Shez: Dual Sword Master
Shez: Keen Mercenary
Shez: Mercenary Shade
Shez: Mercenary Shine
Shez: Rising Mercenary
Shez: Sharpest Blades
Shez: Snowfield Envoy
Shigure: Dark Sky Singer
Shigure: Uplifting Artist
Shinon: Scathing Archer
Shinon: Sharptongue Ninja
Shiro: Raw Talent
Shura: Righteous Rebel
Siegbert: Future King
Sigrun: Loyal Protector
Sigrun: Steadfast Bride
Sigurd: Destined Duo
Sigurd: Fated Holy Knight
Sigurd: Holy Knight
Sigurd: Of the Holy War
Sigurd: Proper Pourer
Silas: Loyal Knight
Silque: Adherent of Mila
Silque: Selfless Cleric
Silvia: Traveling Dancer
Sirius: Mysterious Knight
Skrimir: Echoing Howl
Soleil: Adorable Adorer
Solon: Church Shadow
Sonia: Inhuman Beauty
Sonya: Beautiful Mage
Sonya: Dazzling Rabbits
Sonya: Vengeful Mage
Sophia: Cobweb Prophet
Sophia: Nabata Prophet
Sophia: Prescient Bride
Soren: Addled Strategist
Soren: Hushed Voice
Soren: Radiant Confidant
Soren: Shrewd Strategist
Soren: Wind of Tradition
Sothe: Dawning Zephyr
Sothe: Rushing Dawn
Sothe: Zephyr
Sothis: Bound-Spirit Duo
Sothis: Girl on the Throne
Sothis: Silver Specter
Stahl: Viridian Knight
Subaki: Perfect Expert
Sue: Doe of the Plains
Sully: Crimson Knight
Sumia: Maid of Flowers
Surtr: Pirate of Red Sky
Surtr: Ruler of Flame
Sylvain: Consummate Flirt
Sylvain: Hanging with Tens
Sylvain: Spring Flingster
Syrene: Graceful Rider
Tailtiu: Teatime Mingler
Tailtiu: Thunder Noble
Takumi: Empty Vessel
Takumi: Prince at Play
Takumi: Prince of Soup
Takumi: Troubled Heart
Takumi: Wild Card
Takumi: Wishful Spark
Tana: Frelian Starlight
Tana: Noble and Nimble
Tana: Soaring New Year
Tana: Soaring Princess
Tana: Soothing Warmth
Tana: Winged Princess
Tanith: Bright Blade
Tanith: Forthright Heart
Tanya: Dagdar's Kid
Tatiana: Devoted Saint
Tethys: Beloved Dancer
Tethys: Dancing Sands
Tharja: "Normal Girl"
Tharja: Beach Dark Mage
Tharja: Dark Shadow
Tharja: Florid Charmer
Tharja: Gloomy Mage
Tharja: Obsessive Bride
Tharja: Shadow Ninja
Thea: Stormy Flier
Thea: Wings of Winter
Thórr: Sun-Kissed Gods
Thórr: War God
Thrasir: Omnicidal Witch
Tibarn: Lord of the Air
Tibarn: Shipless Pirate
Tiki: Awakened Blood
Tiki: Beachside Scion
Tiki: Bridal Reflections
Tiki: Dragon Scion
Tiki: Dragon's Progeny
Tiki: Fated Divinity
Tiki: Harmonic Hope
Tiki: Legendary Dragon
Tiki: Naga's Voice
Tiki: Summering Scion
Tiki: Torpid Dragon
Timerra: Desert Warrior
Timerra: Trick or Meat
Tina: Playful Scamp
Tine: Determined Bride
Tine: Rumbling Thunder
Titania: Mighty Mercenary
Titania: Warm Knight
Tobin: The Clueless One
Tormod: Indomitable Will
Travant: King of Thracia
Triandra: Nightmare
Triandra: Reverent Dream
Triandra: Sunlit Nightmare
Tsubasa: Madcap Idol
Ullr: The Bowmaster
Ursula: Blackened Crow
Ursula: Blue Crow
Ursula: Clear-Blue Crow
Ursula: Royal-Blue Crow
Uther: Frugal Militarist
Vaida: Dracofang General
Vaike: Sunbaked Stunner
Valbar: Open and Honest
Validar: Fell Architect
Valter: Dark Moonstone
Vanessa: Dutiful Rider
Veld: Manfroy's Rock
Velouria: Renewed Wolfpup
Velouria: Wolf Cub
Veronica: Bestowed Love
Veronica: Brave Princess
Veronica: Harmonic Pirates
Veronica: Princess Rising
Veronica: Royal Reception
Veronica: Spring Princess
Veyle: Fell Successor
Veyle: Gentle Dragon
Veyle: Spring Tranquility
Vigarde: Silent Emperor
Vigarde: Warmhearted Sire
Vika: Sea-Dark Wing
Virion: Elite Archer
Volke: Man of Mysteries
Vyland: Coyote's Justice
Walhart: The Conqueror
Wil: Unequaled Archer
Wolf: Coyote's Loyal
Wolt: Sunbeam Archer
Wrys: Kindly Priest
Xander: Dancing Knight
Xander: Focused Firstborn
Xander: Gallant King
Xander: Paragon Knight
Xander: Spring Prince
Xander: Student Swimmer
Xane: Autumn Trickster
Xane: Desert Mirage
Xane: Fickle Dragon
Yarne: Hoppy New Year
Yarne: Timid Taguel
Yarne: Trick or Taguel
Yen'fay: Blade Legend
Ylgr: Breaking the Ice
Ylgr: Fresh Snowfall
Ymir: Life-Mother
Ymir: Seasons of Life
Yukimura: Puppet Master
Yuliya: Princess of Grust
Yunaka: Hidden Mask
Yunaka: Spirited Envoy
Yune: Chaos Goddess
Yuri: Ashen Valiant
Yuri: Tropical Wolf
Yuri: Underground Lord
Zeiss: Ebon Bolt
Zeke: Past Unknown
Zelestia: Loving Leader
Zelgius: Jet-Black General
Zelgius: Ninja Knight
Zelot: Avowed Groom
Zephia: Scheming Dragon
Zephiel: The Liberator
Zephiel: Winter's Crown
Zihark: Ninja Blademaster
Þjazi: Ruthless Jötun

The missingidx list created above can be used to add the missing hero pages to the hero-pages folder.

In [44]:
for i in range(heroes_table.shape[0]):
    # Create file name
    temp = heroes_table['Hero'].iloc[i].split()
    for j in range(len(temp)):
        temp[j] = temp[j].strip(':"')
        name = ''.join(temp)
    
    # Pull HTML from site
    time.sleep(0.5)
    soup = bs4.BeautifulSoup(requests.get(heroes_table['Link'].iloc[i]).content, "lxml")
    script = soup.find_all('script')
    [s.decompose() for s in script]
    navbox = soup.find('div', class_= 'navbox')
    navbox.decompose()
    aside = soup.find_all('aside')
    [a.decompose() for a in aside]
    commhead = soup.find('div', class_='community-header-wrapper')
    commhead.decompose()
    ul = soup.find_all('ul', class_='wds-tabs')
    [u.decompose() for u in ul]
    foot = soup.find('footer', class_='global-footer')
    foot.decompose()
    pagef = soup.find('div', class_='page-footer')
    pagef.decompose()
    sidew = soup.find('div', class_='page-side-tools__wrapper')
    sidew.decompose()
    pheadt = soup.find('div', class_='page-header__top')
    pheadt.decompose()
    item1 = soup.find('div', class_='global-explore-navigation')
    item1.decompose()
    navtop = soup.find('div', class_='community-navigation fandom-sticky-header')
    navtop.decompose()
    ads = soup.find('div', class_='bottom-ads-container')
    ads.decompose()
    navi = soup.find('nav', class_='global-top-navigation')
    navi.decompose()
    act = soup.find('div', class_='page-header__actions')
    act.decompose()
    [svg.decompose() for svg in soup.find_all('svg')]
    soup.find('div', class_='toc').decompose()

    with open(F"hero-pages/{name}.html", "w", encoding = 'utf-8') as file:
        file.write(str(soup.prettify()))
    print(name)

AbelThePanther
AelfricCustodianMonk
AlcrystTenderArcher
AlcrystTenderGroom
AlearAwokenDivinity
AlearDragonChild
AlearDragonYouth
AlearEngagingFire
AlearFellDragonChild
AlearGiftedDragons
AlearRedDaysPast
AlearSeasideDragon
AlfonseAskranDuo
AlfonseHeirtoOpenness
AlfonsePrinceofAskr
AlfonseSpringPrince
AlfonseUpliftingLove
AlfredFloralProtector
AlmHeroofProphecy
AlmImperialAscent
AlmLovebirdDuo
AlmPowerfulResolve
AlmSaint-King
AltenaLuminousRider
AltinaCross-TimeDuo
AltinaDawn'sTrueblade
AltinaUnrivaledDawn
AmeliaBlossomingTalent
AmeliaRoseoftheWar
AnankosSeethingSilence
AnnaCommander
AnnaSecretCharmer
AnnaSecretSeller
AnnaTwicetheAnna
AnnaWealth-Wisher
AnnandKnight-Defender
AnnetteFestiveHelper
AnnetteOverachiever
ArdenStrongandTough
AresBlackKnight
AreteRequiem'sBeauty
ArionGungnir'sHeir
ArlenMageofKhadein
ArthurFuriousMage
ArthurHaplessHero
ArturSilverSaint
ArvalCycleKeeper
ArvisEmperorofFlame
AsbelWindsweptYouth
AshBorrowedPower
AshEarnestGreetings
AshRetainertoAskr
AsheBuddingChivalry
AsheChivalricAmends
AsheFabledSeaKnight
AsheraOrderGoddess
AshnardMadKing
AskrGodofOpenness
AskrOpenHarvest
AskrRenewedGods
AstramMidia'sHero
AstridResoluteDamsel
AthenaBorderlandSword
AthosOmniscientOne
AtlasForestMuscle
AugustAstuteTactician
AversaDarkOne
AyraAstra'sWielder
AyraSupremeAstra
AyraTogetherinTea
AzamaCarefreeMonk
AzelleYouthfulFlame
AzuraCelebratorySpirit
AzuraHatariDuet
AzuraLadyofBallads
AzuraLadyoftheLake
AzuraSong'sReflection
AzuraValliteSongstress
AzuraYoungSongstress
BaldrCelestialSunGod
BaldrRaysofJudgment
BalthusKingofGrappling
BalthusSummer'sBigBet
BantuTiki'sGuardian
BarstTheHatchet
BartreEarsomeWarrior
BartreFearlessWarrior
BasilioFeroxiWest-Khan
BastianCrimea'sKeystone
BennySensitiveSoul
BerkutDebonairNoble
BerkutPridefulPrince
BerkutPurgatorialPrince
BernadettaEternalLoner
BernadettaFrostyShut-In
BernadettaLateHibernator
BernadettaShelteredLoner
BertramDreadCavalier
BerukaQuietAssassin
BlackKnightMortalLegend
BlackKnightSinisterGeneral
BlackKnightTheNight'sBlade
BoeySkillfulSurvivor
BorsOstia'sBastion
BoydFutureGreat
BradyDauntingPriest
BramimondTheEnigma
BrigandBossKnownCriminal
BrigidAwakenedBow
BrigidOrgahilPirate
BrunnyaDevotedGeneral
BrunoMaskedHare
BrunoMaskedKnight
BrunoMaskedReveler
BylethAnchorofHope
BylethFellStar'sDuo
BylethFountofLearning
BylethFrostyProfessors
BylethProvenProfessor
BylethSublimeLight
BylethTestedProfessor
BylethTheFódlanLight
BylethTheFódlanStar
BylethVengeanceVessel
CaedaBelovedQueen
CaedaMarth'sFaithful
CaedaPrincessofTalys
CaedaSea-BlossomPair
CaedaTalys'sBride
CaedaTalys'sHeart
CaeldoriPerfectAngel
CaellachTigerEye
CainTheBull
CaineghisGallia'sLionKing
CamillaAlluringDarkness
CamillaBewitchingBeauty
CamillaFlowerofFantasy
CamillaHolidayTraveler
CamillaLightofNohr
CamillaMidnightBloom
CamillaSpringPrincess
CamillaSteamySecrets
CamillaTropicalBeauty
CamillaYoungBeauty
CamusSableKnight
CanasWisdomSeeker
CandaceSlySnatcher
CasparHotheadedInciter
CasparSummerIntensity
CastorLovingSon
CathCaperCaptain
CathMasterThief
CatherineThunderKnight
CatriaAzureWingPair
CatriaMiddleWhitewing
CatriaMildMiddleSister
CatriaSpringWhitewing
CatriaWindsweptKnight
CeciliaEtrurianBride
CeciliaEtrurianGeneral
CeciliaFestiveInstructor
CedHeroontheWind
CedSageoftheWind
CelicaCaringPrincess
CelicaImprisonedSoul
CelicaOfEchoes
CelicaQueenofValentia
CelicaSunlitPriestesses
CelicaValentia'sHope
CelicaWarriorPriestess
CélineBlissfulTeaParty
CélineJoyousRoyal
CélineTeatimeNinja
CervantesInvincibleGeneral
ChadLycianWildcat
CharlotteMoneyMaiden
CharlotteWilyWarrior
ChercheShadedbyWings
ChercheWyvernFriend
ChloéFairy-TaleFlier
ChloéSpringWings
ChromCrownedExalt
ChromExaltedPrince
ChromFate-DefyingDuo
ChromFatedHonor
ChromFellExalt
ChromGiftedLeader
ChromKnightExalt
ChromPivotalBlow
ChromSpringExalt
ChulainnLeadingGladiator
ChulainnUnbeatenWarrior
CitrinneCaringNoble
ClairHighbornFlier
ClanneSummerFan
ClarineRefinedNoble
ClarisseSniperintheDark
ClaudeAlmyra'sKing
ClaudeDistantDeer
ClaudeGoldenBreeze
ClaudeKingofUnification
ClaudeTheSchemer
ClaudeTropicalTrouble
ClaudeYuletideSchemer
CliveIdealisticKnight
ColmCapableThief
ConradMaskedKnight
ConradUnmaskedKnight
ConstanceFallenNoble
CordeliaKnightParadise
CordeliaKnightParagon
CordeliaPerfectBride
CordeliaUnyieldingSnow
CormagAloofLanceman
CorneliaSaintConsumed
CorrinBloodboundBeast
CorrinCelestialSorcerer
CorrinChildofDawn
CorrinChildofDusk
CorrinDaylightNinjaAct
CorrinDreamPrince
CorrinDreamPrincess
CorrinEnjoyingTradition
CorrinFatefulPrince
CorrinFatefulPrincess
CorrinNightfallNinjaAct
CorrinNoviceVacationer
CorrinOfFates
CorrinSilentBloodline
CorrinStarrySeer
CorrinWailingSoul
CorrinYoungKinship
CynthiaHeroChaser
CyrilRhea'sAttendant
DagdarReformedBandit
DagrBlusterPrincess
DagrNewYearJötnar
DagrSun'sRadiance
DagrSunnyBloom
DarrosSeawalker
DeathKnightTheReaper
DedueDauntlessBeast
DedueDimitri'sVassal
DedueLoyalLifeGuard
DeenBladedSandstorm
DeirdreFatedSaint
DeirdreLadyoftheForest
DeltheaFreeSpirit
DeltheaProdigyinBloom
DeltheaTatarrah'sPuppet
DewBenevolentThief
DheginseaHarvestGoldoan
DiamantFortifiedKing
DiamantGallantNinja
DiamantRisingPower
DieckWoundedTiger
DimitriBlessedProtector
DimitriKingofFaerghus
DimitriSavageBoar
DimitriSaviorKing
DimitriSky-BlueLion
DimitriStargazingLion
DimitriTheProtector
DíthorbaCuttingKnight
DonnelSunnyVillager
DonnelVillageHero
DorcasPumpkinSmasher
DorcasSereneWarrior
DorotheaDaringEx-Singer
DorotheaSolarSongstress
DorotheaTwilitHarmony
DorotheaYuletideDancer
DorothyDevotedArcher
DozlaHarvestAttendant
DraugGentleGiant
DuesselObsidian
DumaGodofStrength
DumaStrengthandLove
DwyerSleepyButler
EchidnaUnyieldingIdealist
EdainLadyofYngvi
EdelgardAdornedEagle
EdelgardAdrestianEmperor
EdelgardFlameEmperor
EdelgardHegemonHusk
EdelgardSnowfallFuture
EdelgardSunEmpresses
EdelgardTheFuture
EdwardBladeofJustice
EffieArmyofOne
EffieDedicatedHeart
EikþyrnirBlessedStrength
EikþyrnirFitforWaves
EikþyrnirQuietingStrength
EikþyrnirResolvedtoTrain
EirLifeAscendant
EirMercifulDeath
EirRenewedLife
EirikaAnamnesisLady
EirikaBeachRestorer
EirikaGentleasSnow
EirikaGracefulResolve
EirikaOftheSacred
EirikaPledgedRestorer
EirikaResolutePrincess
EirikaRestorationLady
EirikaTwinRefulgence
EitrHandofNothing
EitrSpringSunrise
EitriYouthfulSage
EldiganLionheart
EldiganStruttingLion
EleonoraShootingStarlet
ElffinTruthBeholden
EliceAlteanPrincess
ElimineScouringSaint
ElinciaDevotedQueen
ElinciaEstivalPrincess
ElinciaLostPrincess
ElinciaSeasideQueen
ElinciaUndauntedQueen
EliseBubblingFlower
EliseBuddingFlower
EliseSparklingSmile
EliseSweetheartRoyals
EliseTropicalFlower
EliwoodBlazingKnight
EliwoodDevotedLove
EliwoodKnightofLycia
EliwoodMarquessPherae
EliwoodPledgedFriend
ElmResoluteGrouch
ElmRetainertoEmbla
EmblaClosed-OffBride
EmblaGodofClosure
EmmerynGentleExalt
EmmerynSelflessExalt
EnaAutumnTactician
EphraimArdentPrince
EphraimDynasticDuo
EphraimLegendaryLord
EphraimRestorationLord
EphraimSacredTwinLord
EphraimSparklingGallantly
EphraimSunshineValiant
EremiyaBishopofWoe
ErinysEarnestKnight
ErkStudiousMage
EstJuniorWhitewing
EstSpringtimeFlier
EstSweetBabySis
EthlynGlimmeringLady
EthlynSpiritedPrincess
EtieFitnessFighter
EwanEagerStudent
ExcellusConqueror’sWile
EyvelMistressofFiana
FaeChildlikeDragon
FaeDivineDragon
FaeHolidayDear
FáfnirFreshAmbition
FáfnirKingofDesolation
FargusBadonBuccaneer
FarinaTheGreatWing
FayeDevotedHeart
FayeDrawnHeartstring
FebailMercenaryWaif
FeeAspiringKnight
FeliciaConfidentlyCold
FeliciaMaidMayhem
FeliciaOfftheMenu
FelixIcyGiftGiver
FelixLone-WolfBlade
FelixSavant'sService
FelixSwordSavant
FerdinandHighbornSipper
FerdinandNoblestofNobles
FernandTraitorousKnight
FinnDevotedService
FinnLanceofLegend
FioraAirborneWarrior
FioraDefrostedIlian
FirDualWarriors
FirStudentofSpring
FirSwordStudent
FirSwordmaiden
FjormBrideofRime
FjormGleamingIcePair
FjormIceAscendant
FjormNewTraditions
FjormPrincessofIce
FjormSeasideThaw
FlameEmperorBringerofWar
FlaviaBoldBride
FlaviaFeroxiEast-Khan
FlaynPlayingInnocent
FlaynSillyKitty-Cat
FloraColdasIce
FloraPolar-Perfect
FloraSignatureDish
FlorinaAzure-SkyKnight
FlorinaLovelyFlier
FogadoAffablePrince
FogadoSummerofBliss
FomortiisDarkofNight
FomortiisDemonKing
FordeUnfetteredKnight
ForrestFashionForward
ForsythLoyalLieutenant
FrammeSpringFangirl
FrederickHorizonWatcher
FrederickPoliteKnight
FrederickYouthinService
FreyjaFleetingSummer
FreyjaLadyofNightmare
FreyjaParallelHearts
FreyrDream-King
FreyrEstivalDreams
FugaForceofGales
GaiusCandyStealer
GaiusThiefExposed
GalleAzureRider
GalzusDarkBladeofOd
GanglötDeathAnew
GangrelPlegia'sMadKing
GaronKingofNohr
GatekeeperNothingtoReport
GatrieArmoredAmour
GeeseALifeatSea
GennyDressedwithCare
GennyEndearingAlly
GeoffreyRealm'sProtector
GerikDesertTiger
GeromeMaskedRider
GharnefDarkPontifex
GilliamWallofSilence
GinnungagapRulerofNihility
GlenSunstone
GoldmaryCoyBeachDivas
GonzalezKindlyBandit
GordinAlteanArcher
GotohApostleofNaga
GotohWhiteSage
GrayWryComrade
GregorSwellSword
GreilHeroicExemplar
GrimaTyrantofDespair
GrimaTyrantofRuin
GrissIndulgingPain
GuiniverePrincessofBern
GuinivereQueenofBern
GullveigGlitteringSunlight
GullveigGoldenSeer
GullveigSeerBeyondTime
GunnthráBeamingSmile
GunnthráVoiceofDreams
GunnthráYear'sFirstDream
GunterInveterateSoldier
GustavMajesticLove
GustavSovereignSlain
GuyKutolahBlade
GwendolynAdorableKnight
HaarBlackTempest
HaarTempestRunner
HaitakaPersistentGeneral
HanaFocusedNinja
HanaFocusedSamurai
HanaStrivingHeart
HansAmbitiousBrute
HapiDrawn-OutSigh
HapiEternalSunlitPair
HardinDarkEmperor
HardinTheCoyote
HarkenTroubledWarrior
HawkeyeDesertGuardian
HawkeyeTaciturnGuardian
HayatoDivinerofReppu
HeathWanderingKnight
HeathWyvernNinja
HeatherWanderingNinja
HectorBraveWarrior
HectorDressed-UpDuo
HectorGeneralofOstia
HectorJustHeretoFight
HectorMarquessofOstia
HectorSteelWarrior
HectorSwornFriend
HeiðrInnocentGoddess
HeiðrúnHealingNectar
HeiðrúnPeacefulHorizon
HeiðrúnSistersofHealing
HelDeathSovereign
HelbindiSavageScourge
HelbindiSeasideScourge
HenrietteOverflowingLove
HenryHappyVampire
HenryPeculiarEgg
HenryTwistedMind
HestiaDuma'sWitch
HildaDeer'sTwo-Piece
HildaHelpingHand
HildaHolidayLayabout
HildaIdleMaiden
HildaQueenofFriege
HinataSamuraiGroom
HinataWildSamurai
HinokaBlueSkyWarrior
HinokaFairPiratePair
HinokaRelaxedWarrior
HinokaThunderingWings
HinokaWarriorofGusto
HinokaWarriorPrincess
HöðrDuskShadowGod
HolstHeroofLeicester
HomerTravelingBard
HortensiaLittleCharmer
HortensiaWinter'sDearest
HræsvelgrQuietingBlade
HræsvelgrWingsofHealing
HrídIcyBlade
HrídIslandIcePrince
HrídResolutePrince
HubertCrimsonSchemer
HubertSinisterServant
HughWorldlyMage
IagoNohr'sTactician
IdunnDarkPriestess
IdunnDivineDemon
IdunnDragonkinDuo
IgnatzSnowscapeArtist
IgreneNabataProtector
IgreneNinjaofNabata
IgreneSwornProtectors
IkeBraveMercenary
IkeClose-KnitSiblings
IkeDesertMercenary
IkeOfRadiance
IkeStalwartHeart
IkeVanguardLegend
IkeYoungMercenary
IkeZealUnleashed
IlyanaAwakenedAppetite
IlyanaHungeringMage
IlyanaTreatHarvester
IngridBeaconofHonor
IngridCordialTeatime
IngridGalatea'sHeir
IngridSolsticeKnight
InigoFestivalFlower
InigoFlowerPicker
InigoIndigoDancer
InnesFlawlessForm
InnesFrelianMoonlight
InnesNewYear'sAim
InnesRegalStrategician
IsadoraEscortofPherae
IshtarEchoingThunder
IshtarThunderGoddess
IshtarThunder'sWaltz
ItsukiFindingaPath
IvySnowQueen
IvyTidalBreeze
JaffarAngelofDeath
JaffarAngelofNight
JagenVeteranKnight
JakobDevotedMonster
JakobDevotedServant
JamkePrinceofVerdane
JarodNevassaGeneral
JedahPriestofDuma
JeorgePerfectShot
JeraltBladeBreaker
JesseBlitheMercenary
JillFieryDracoknight
JorgeTravelingPeddler
JoshuaResoluteTempest
JoshuaTempestKing
JoshuaTropicalGambler
JuliaBridesofLight
JuliaCrusaderofLight
JuliaHeartUsurped
JuliaNaga'sBlood
JuliaScionoftheSaint
JulianTenderThief
JuliusScionofDarkness
JunoNimbleGrace
JunoSoaringBride
KadenKitsuneBraggart
KadenRefreshedKitsune
KageroBeverageNinja
KageroBondUnwavering
KageroHonorableNinja
KageroSpringNinja
KagetsuOnigiriSamurai
KamuiWanderingBlade
KanaDragonPrincess
KanaDragonSpawn
KanaRisingDragon
KanaRisingSunlight
KarelSwordDemon
KarinDrivenKnight
KarlaSpringReveries
KarlaSun-PiercingSteel
KarlaSwordVassal
KatarinaTorchlitWanderer
KatarinaWaywardOne
KazeEasygoingNinja
KeatonLupineCollector
KeatonResolvedWolfskin
KellamPumpkinKnight
KempfConnivingGeneral
KentCrimsonShield
KiragiUpbeatArcher
KiriaCoolFaçade
KjelleFairFighter
KleinSilverNobleman
KliffCuriousSpirit
KnollDarknessWatcher
KrisArdentFirebrand
KrisUnknownHero
KrisUnsungHero
KronyaGleamingBlade
KurthnagaAutumnGoldoan
KvasirSeerofthePast
KvasirUnknownFuture
KyleZealousKnight
KyzaTigerofFortune
L'ArachelHarvestPrincess
L'ArachelPrincessofLight
L'ArachelSeekerofJustice
L'ArachelSummerPrincess
LachesisBallroomBloom
LachesisLionheart'sSister
LaegjarnBurningSun
LaegjarnFlameandFrost
LaegjarnFlameAscendant
LaegjarnNewExperiences
LaegjarnSheathedSteel
LaevateinBonfire'sBlaze
LaevateinKumadeWarrior
LaevateinNinjaofMúspell
LaevateinSearingSteel
LanaBenevolentBride
LapisForageroftheSea
LapisMightyBride
LapisMightyFlower
LaraStepLively
LarceiBrideofAstra
LarceiKeenKin
LarceiScionofAstra
LarumDancingBride
LarumSprightlyDancer
LaslowDancingDuelist
LaurentTheElucidator
LæraðrQuietingHeart
LeanneForest'sSong
LegaultTheHurricane
LegionMaskedManiac
LeifDestinedScions
LeifPrinceofLeonster
LeifSworntoCountry
LeifUnifierofThracia
LeilaKeenLookout
LeilaRoseamidFangs
LeilaSuperbShadow
LenaBereftAngel
LenaTenderAngel
LeneYearningDancer
LeoDarkSprout
LeoExtraTomatoes
LeoFestivalBonds
LeoSeashore'sPrince
LeoShroudedHeart
LeoSorcerousPrince
LeonTrueofHeart
LeonardoFreedom'sArrow
LeonieRelentlessRays
LetheCatAttack
LetheGallia'sValkyrie
LetheNewYear'sClaw
LetiziaCurseDirector
LewynGuidingBreeze
LewynWind-SongScion
LexYoungBlade
LibraFetchingFriar
LífArcaneBlade
LífLethalSwordsman
LífUndyingTiesDuo
LifisTerrorofIz
LilinaBeachsideBloom
LilinaBeamingBride
LilinaBlushofYouth
LilinaBrilliantFlame
LilinaDelightfulNoble
LilinaFirelightLeader
LilithAstralDaughter
LilithSilentBroodling
LimstellaLivingConstruct
LindeBoundbyFate
LindeLightMage
LindeSummerRays
LinhardtHevring'sHeir
LinhardtSpringSnoozer
LinoanLadyofTarrah
LinusMadDog
LinusSavageDog
LissaLittlestPrincess
LissaPureJoy
LissaSprightlyCleric
LissaSweetCelebrant
LloydVengefulWolf
LloydWhiteWolf
LokiSpringTrickster
LokiTheTrickster
LokiTricksterGod
Lon'quSolitaryBlade
Lon'quSpringJitters
LorenzHighbornHeat
LouiseEternalDevotion
LouiseLadyofViolets
LuciaLoyaltyEnrobed
LuciaTirelessAdvisor
LucinaBravePrincess
LucinaFate'sResolve
LucinaFutureFondness
LucinaFutureWitness
LucinaGloriousArcher
LucinaShadowsofFate
LucinaSpringExalt
LuciusCalmingLight
LuciusTheLight
LudveckRebelliousDuke
LughAnimaChild
LukasBuffetforOne
LukasSharpSoldier
LukeRowdySquire
LumeraCorruptedDragon
LumeraDragonMonarch
LumeraInDistantSkies
LuteProdigy
LuteSummerProdigy
LuthierOddWayfarer
LuthierSpringHopes
LynBlazingWhirlwind
LynBraveLady
LynBrideofthePlains
LynLadyoftheBeach
LynLadyofthePlains
LynLadyoftheWind
LynNinja-FriendDuo
LynOfBlazing
LynPlainsWind
LynWind'sEmbrace
LyonDemonKing
LyonEsteemedRoyals
LyonGrado'sGaze
LyonShadowPrince
LyonSunlitPrince
LyreLapCatofLuxury
LysitheaChildProdigy
LysitheaEarnestSeeker
LysitheaGiftedStudents
LysitheaTeaSweetener
MachyuaBladeofGales
MaeBundleofEnergy
MaeSpringCheer
MaliceBloomingBlade
MaliceDeftSellsword
MamoriMicrowavin'Idol
ManuelaSilverCaroler
MarciaPetulantKnight
MareetaAstraAwakened
MareetaSwordofStars
MareetaTheBlade'sPawn
MariaMinerva'sSister
MariaRitualSacrifice
MariaSunnySmile
MarianneAdoptedDaughter
MarianneCursedBlessing
MarianneSereneAdherent
MaribelleDireDamsel
MarisaCrimsonFlash
MarisaCrimsonRabbit
MarisaWillfulBlades
MarkWindsofHope
MarlaDuma'sWitch
MarniPiningforPraise
MarthAlteanGroom
MarthAlteanPrince
MarthEnigmaticBlade
MarthHero-King
MarthLegaciedHero
MarthLoveandCourage
MarthMaskedGladiator
MarthOfBeginnings
MarthPrinceofLight
MarthRoyalAlteanDuo
MathildaLegendaryKnight
MatthewFaithfulSpy
MatthisBrothertoLena
MauvierPenitentKnight
MedeusEarth-DragonKing
MedeusLastEarthDragon
MeladyCrimsonRider
MelíaiWarriorWanderer
MercedesKindlyDevotee
MercedesUnfussedBasker
MerlinusPherae'sClerk
MerricChangingWinds
MerricWindMage
MerricWindPontifex
MerrinSuaveKnight
MetodeyShrewdBraggart
MiaBuddingBlade
MiaHarmonicBlades
MiaLadyofBlades
MiaMoonlitWitch
MiaSummerSlice
MicaiahDawnWind'sDuo
MicaiahDawningMaiden
MicaiahOfDawn
MicaiahPriestessofDawn
MicaiahQueenofDawn
MicaiahRadiantQueen
MicaiahSummer'sDawn
MicaiahWavecrestMaiden
MichalisAmbitiousKing
MichalisFruitingAmbition
MidirArcherofYngvi
MidoriReliableChemist
MikotoCaringMother
MilaGoddessofLove
MinervaPrincess-Knight
MinervaRedDragoon
MinervaVerdantDragoon
MirabilisDaydream
MirabilisSpringDaydream
MirabilisSugarplumVision
MirandaWillfulPrincess
MirielRapierIntellect
MistHelpfulSister
MistPurestSpirit
MonicaFavoredVassal
MordecaiGentleFiretender
MordecaiKindheartedTiger
MorganDevotedDarkness
MorganFatedDarkness
MorganLadfromAfar
MorganLassfromAfar
MozuTragicStart
MuarimRawInstinct
MurdockLoyalGeneral
MúspellFlameGod
MúspellRagingInferno
MustafaPlegianChampion
MycenZofia'sChampion
MyrrhAdoredDragon
MyrrhGreatDragon
MyrrhGuardianDragon
MyrrhSpookyMonster
MyrrhSpringHarmony
NaesalaSea'sShadow
NaesalaSky'sShadow
NagaDragonDivinity
NagaHarvestDivinity
NagaRulerofDragons
NagiDragonAvatar
NagiHopefulEternity
NahGratefulOne
NahLittleMiss
NailahBlessedQueen
NailahHatariScorcher
NailahUnflinchingEye
NannaBelovedPrincess
NannaMystletainnScion
NannaNordionPrincess
NarcianVernalGeneral
NarcianWyvernGeneral
NatashaSacredHealer
NavarreScarletNinja
NavarreScarletSword
NeimiTearfulArcher
NelStoicBride
NelStoicDragon
NemesisKingofLiberation
NepheneeFestivalHarmony
NepheneeFierceHalberdier
NepheneeSincereDancer
NergalTraitortoNabata
NerþuzBeachChaperone
NerþuzDivineAbundance
NerþuzGodoftheLand
NerþuzNew-YearDoter
NiðavellirFoundingKing
NíðhöggrDazeofHealing
NíðhöggrQuietingDose
NiflGodofIce
NiflTropicalIceGod
NiimeMountainHermit
NilesCrueltoBeKind
NilesForbiddenTease
NilsBrightBard
NilsSnowflakeMelody
NilsWanderingStar
NinaEyeSpy
NinaShadowyFigures
NinianBright-EyedBride
NinianFrozenHeart
NinianIce-DragonOracle
NinianOracleofDestiny
NinoBurstofSummer
NinoFang'sHeart
NinoFlowerofFrost
NinoPaleFlower
NinoPiousMage
NinoSpiritedSorcerer
NoahMercenary-Errant
NoireDemurelyDeft
NoireOfTwoMinds
NoireShadeSeeker
NomahPriestofMila
NorneSeasideVolunteer
NorneTheVolunteer
NóttMoon'sElegance
NowiEternalWitch
NowiEternalYouth
NuibabaMistressofFear
NynaTheLastPrincess
NyxRulebreakerMage
OboroFierceBride-to-Be
OboroFierceFighter
OdinPotentForce
OgierOstia'sNewBlade
OgmaBladeonLeave
OgmaFormerGladiator
OgmaLoyalBlade
OliverAdmirerofBeauty
OliviaBlushingBeauty
OliviaFestivalDancer
OliviaSky-HighDancer
OliviaWavecrestDancer
OlwenBlueMageKnight
OlwenRighteousKnight
OpheliaDramaticHeroine
OpheliaStarlitMaiden
OrochiMerryDiviner
OrsonPassion'sFolly
OscarAgileHorseman
OsianScoldedSoldier
OswinImpregnableKnight
ÓtrKingsbrother
OwainChosenOne
OwainDevotedDefender
PallaEldestBun-Bun
PallaEldestWhitewing
PallaKindEldestSister
PallaSisterlyTrio
PallaSoaringSummer
PandreoPartyPriest
PanetteClassyBrawler
PanneProudTaguel
PanneWelcomingDawn
PattyYouthfulThief
PelleasAshnard'sOrphan
PentFancyFiancé
PentMageGeneral
PeonyÁlfarDreamDuo
PeonyCherishedDream
PeonyFruitfulDream
PeonySweetDream
PercevalKnightlyIdeal
PeriPlayfulSlayer
PerneDacianScoundrel
PetraFarawaySun
PetraPrincessofBrigid
PetrineIcyFlame-Lancer
PhilaPegasusMaster
PhinaRovingDancer
PlumeriaLewdDream
PlumeriaRapturousDream
PlumeriaSpringDance
PlumeriaTemptationAnew
PriamRadiantHero
PriscillaDelicatePrincess
PythonApatheticArcher
QuanLightfootPrince
QuanLuminousLancer
RafalAtoningDragon
RafielBlessedWings
RaighDarkChild
RanulfConsiderateGaze
RanulfFriendofNations
RaphaelMuscle-Monger
RatatoskrMendingHand
RathWolfofSacae
RavenPeerlessFighter
RebeccaBreezyScamp
RebeccaWildflower
ReginnBearingDawn
ReginnBearingHope
ReginnDvergrHeir
ReinaSanguineShinobi
ReinhardtLightning'sRondo
ReinhardtThrudReborn
ReinhardtThunder'sFist
ReinhardtThunder'sSword
RennacRichMerchant
ReysonWhitePrince
RhajatBlackMagician
RheaAuraofLove

# TESTING ZONE

In [42]:
soup = bs4.BeautifulSoup(requests.get("https://feheroes.fandom.com/wiki/Abel:_The_Panther").content, "lxml")
script = soup.find_all('script')
[s.decompose() for s in script]
navbox = soup.find('div', class_= 'navbox')
navbox.decompose()
aside = soup.find_all('aside')
[a.decompose() for a in aside]
commhead = soup.find('div', class_='community-header-wrapper')
commhead.decompose()
ul = soup.find_all('ul', class_='wds-tabs')
[u.decompose() for u in ul]
foot = soup.find('footer', class_='global-footer')
foot.decompose()
pagef = soup.find('div', class_='page-footer')
pagef.decompose()
sidew = soup.find('div', class_='page-side-tools__wrapper')
sidew.decompose()
pheadt = soup.find('div', class_='page-header__top')
pheadt.decompose()
item1 = soup.find('div', class_='global-explore-navigation')
item1.decompose()
navtop = soup.find('div', class_='community-navigation fandom-sticky-header')
navtop.decompose()
ads = soup.find('div', class_='bottom-ads-container')
ads.decompose()
navi = soup.find('nav', class_='global-top-navigation')
navi.decompose()
act = soup.find('div', class_='page-header__actions')
act.decompose()
[svg.decompose() for svg in soup.find_all('svg')]
soup.find('div', class_='toc').decompose()

with open(F"test/test.html", "w", encoding = 'utf-8') as file:
    file.write(str(soup.prettify()))

# Construction Below

In [3]:
heroes = requests.get('https://feheroes.fandom.com/wiki/Level_40_stats_table')
heroes = bs4.BeautifulSoup(heroes.text, features='lxml')
print(heroes)

<!DOCTYPE html>
<html lang="en-US"><head><title>Just a moment...</title><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="noindex,nofollow" name="robots"/><meta content="width=device-width,initial-scale=1" name="viewport"/><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji"}body{display:flex;flex-direction:column;height:100vh;min-height:100vh}.main-content{margin:8rem auto;padding-left:1.5rem;max-width:60rem}@media (width <= 720px){.main-content{margin-top:4rem}}#challenge-error-text{background-image:url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk4NS40MDYtLjM5NyAxLjA1Ni0uMzk3Ii8+PC9zdmc+");background-repeat:no-repeat;background-size:contain;padding-left:34px}</style><meta content="360" http-equiv="refresh"/></head><body><div class="main-wrapper" role="main"><div class="main-content"><noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript></div></div><script>(function(){window._cf_chl_opt = {cvId: '3',cZone: 'feheroes.fandom.com',cType: 'managed',cRay: '9ea7d264ab7558fe',cH: 'dgvX5fHCbXLhAPByH0IW0k5Bl9vcnOrXwy28ldhL6cU-1775887760-1.2.1.1-u_dWeeVLnIwrSYv68jnz5QPJ32uIurZ0yE8Ox47rbedCo_YTm9tD0gbsC.cnTdWX',cUPMDTk:"\/wiki\/Level_40_stats_table?__cf_chl_tk=CSSgKS7Sds.Zz21FtYfscHyBjufwaxAwgZh1KmyL5p4-1775887760-1.0.1.1-TvaPFYBwysG4fY2Kl9P9kip_hMqlypYZ87IH_Eez1XU",cFPWv: 'g',cITimeS: '1775887760',cTplC:0,cTplO:0,cTplV:5,cTplB: '0',fa:"\/wiki\/Level_40_stats_table?__cf_chl_f_tk=CSSgKS7Sds.Zz21FtYfscHyBjufwaxAwgZh1KmyL5p4-1775887760-1.0.1.1-TvaPFYBwysG4fY2Kl9P9kip_hMqlypYZ87IH_Eez1XU",md: 'cQmP1GucMnKnOvm45RQ8jCD_Xhr7VM7JXggpu4uZtpg-1775887760-1.2.1.1-VZ7AHi8LH_G.JTvJvmlExcmwIq0i9vISu84O.YTn9AjpvbmJLUDJkcV1oJ4E_B54DNKoa_sll.3JcQj1BkK8acctnFlvwfLZTgujhBudQ7R5bfDOHknBz9JpjGK_FoI4guoIfv8kvSu_LlTeY4B2BZvWMgh0n1iGTNKtqqdswSZITVUP0VGCVcmt_j5M6hrfxPDS2ucgTbNcHineAdTbNpolcmCI8ufkfanjxw7OLX4NDv1h1dKXsVJxvm1Ww3aQzpOvkS4SR0dPxcos1K16w0aC.K.fVtJVg3dTZuAZh6bYo173plh5UVNgdMRkp97odpukp0xF1_tQUs7Hr7nBZHs1kXqUcF9nQOoP7BapyeMg8ERW6xIYB_wrBi1kIhzizg9R5m3WXkaVXCxQPovQOxjfhvXxxnyPJAFlBLvmmFUSFD3kyiUE3bqeTRTkZgg3LZnh149VRhXQmApac6KdarItxAnANRjD4SyLsvGPORsbBH_dfTd60cFo8vXnNtIX0hPgUCoU_OzwfuS2e9vSGGZNIFRU9luyEso.BZnZ7skKhHvLBge_J8iL1U2UicWwIRCBeENPsd1OaYAxJ4izXGm7pfMLMm1DreK7Ens7r4qr8ye5uBxRmsvO0yMeOIXDdhNwFIYlZKWUncUv4b6eTqb1kW_AbIABFz_HTqKYiLuxNOvurrislTJ8T.Hzte4nIz5ef0guThzo40NYh2cQfbl5ZtZUmVAfjUUieEySirYFZymAjDe7uF4vRIsmSRD5s7jHsEGznEW5Ydey3cew1MdUj2nlgVAbMdSR9il79K3.2GluY37LKXcw2NLrKvXlf1t1_niDj2kRiRtTS8wEMl7WSfusreqBAQo8xFUP5c0w4DArLAk00s2qN7t294V9iY6GHSETYFCnBKsS254VtNTx4GIVnmP2oO5TP0wFZdb74SNXWu_CIhfpsD4YMGngMsgK4X_C0yr2VsBJ3Fp.NX90.o_Og5awROg8E1l3Yj0RE680wle4z26ROPTpjJjdEVYI3sSbnlCL_.eznLnKzEWPuFQ9KjzxXQPhacZ_BYk',mdrd: '6Hqua568YHHwN5zYdVaCETuzec71AJnWsN.a.lbOSvk-1775887760-1.2.1.1-HNJOBWjgZPYEWB7EnVdcFKkd92ofLFnL7tI6j.pQLZ26FW.zKM8gpFhWcbld5pPtxENPosOx4BQO3WmCpC5WZj1UGaMQ8rhf4g.oeADwQKjUUJHnbYlXU.fk_ruQLF0Hlqejd1BUCA3W2UBm4MFm90iZSMbeMW1ZU61_UkkYd9vYKmYHkjnqN6sW3bQymtZIQzqVbfOz9I67qFiZn0t3Yhue0APKKBSukclkyXKtvwXQD_N9Rt1P6VZoV8waP1mFaOLJa3bj6xxR0aFoi.Sn80AS7vc25j4NPU2RpOlXCdombKDfeeumpybXMrzy7jo.QsbYMBFNreNsoFbpN_TFzJGtLpfjZoQLP6X2hO955wMAs0qJ5PQ0hDjyUGpqzjf.0q2agyD7ajcZmMmJBuJBG0F7sW8p1bLkZsGm7yeKiSih0uVJoaskIrnvQAk8v.KWpg3w0bKpWeUk9Cod6jzS_uEfGpoEbtSeuH4fVh2mGXDTXm2Q_jqOgvJbqKjLlfF0GxpIUG6LDiE16tgYxBXbL0lr.teQMQMYk._e9d5n1MCOuvojh7ePzXUTZtnsJelN55hNGexdZLRtW8A5F1nxjhscDmT39GM1YCe0zisBYbNU0riC_L2qGxHSRvX1T_yJlxQncx4O3I5r8MfxSTXx1LtI2BrqtAxu5N009xqQt_jO2PbtWtugiTUYdjRtzXtK4DbLu44605UOS0TuSgblYg8nM9M7KDcTV5uNSnw3yytS7RXHbJVbcFfdDcWrRwvf8Qm5RYdQbDgf3WQn9o0ZHBnhWDQ8BSF5yWJ3_c1djJ91xR72YkSaxdnkolcc8dNJ9LbuYL9rwRRc6KICssn0MLpyScP3Wz9Ms7GoeF022YjM.0tJfQeNpmI7QGJ0eomwZypRdy8CrIrLGMJIProdnvgeLx0.KXLodDFbaDw4WUd7.FgiQwsS6y1bn5oZ2q_aHpF8brb.JHlHV1vo70hJqFu7VQdYrkB2cPnPje268DF8Sa0J70VE_Nw2APr8QHQ7xi4ds1Mi.2iyijC55o9lo9RRaNTLcpXRPtLfJUlUcQEMLqmjAOxx5GgJE7RwGJzmO9lpf64ue5J85kGL0pmTpvelEQKnosflxAAJ3jlGBp55bD74VaQznFyXcZGla8EB1EEdLvsV1pVVvHD0EY0b0GD8el59thNp2mo62w_4UxyLHps1A36F3XrqYmmeLdZAtZTuZ9qv9FfGanYuZBjckrPmWRoPQ141TAMTJ5ODGQjGD.._dlK2bNMWEBLHRWUt9UXM50XDal3GSP620hK_.j3zS8RBOT0cnAizykAv5lQxa7zwwPL.pZmkg5_tEnD8aZCHc19DT9LOhi6MBDjLpfmJm3pM09NUD15oWPSst.NJbvj44obxDK8O_._8ZeNts7K4rAIKyV1Xd11dertE4Co2t3n6LIgIcPdQZ.pyeem3cJzZFpDfpZJlvwrn4fhL6Flo2K6IV_RGu.vfcX7Mzc0Rbve8TfhJ3zlDLw8jBo7wqqOwhalFs0qXCkGnfbJQkWYXxu7W.cVOHaJLO55VreMJzABvNsrHjUXKrk32Ex6xQSapzUlVkTDZF71njJry5V5e6nXsGtRzqeWHwrBI5S3S4hYliPWEEZ5_bPA_y3oPOv06x0nRueK9p89jSHtEBrtuS2j79dj9BflSIegGbdSrGxU1nZpBMKb5LrtAWzUSKSBaeAOUt9LxCwlxjNzlFDWZ83s2zJ44Ys_SEiFlMzDiYhHeuqInxrObGJKjY1l9.UXtLAE376a1yOo9dxDhh.ZWdorlCpC2bcb.LqRgWjgdHy.mAJfg6t0bi8y5r4JerhwydkDqRXiG2Z.lg0BfrZuC_dU5V2Pzxl9qu4jMn2bjNzfjLJ4iePNLAzto3SmbkrAvF6b6OBkPf1SX_PujZj_Ch_u1mJm2XLCV2aRDSBRqopb6A.G4.0U2Jn0Sl064XCy1Bq5xeMpuY_xzKIvjKA9zP5igcilGzzJUin7o.zW8cpXy6K0ETxaOSFIlJAG7_fz.lFA.ktmhOItCPuWT7F1MqUmdQeEoeMmFtQ9C423CKChGSXoy2Mt7mx01jtPgJUPdktPGzvKhNlH_chkCmRUmI_DG61q3DndfOssOwz628sUlG_5RGVCPnd1MSa9EkY86fsFaeZaayfmSsf.ikRnsCD2GmX98SEEnK0K_HNeZgzc43lAUjCpk3tyYuKTZhw4zug.7_ObSsPiuvMvrfLxaXkNlbCRnpA4I2v1Af60kxfOr6ziy7l7NqLly3.EN07TifjztKKRdrve229BM7RKonbBXZmJj2XPQxOvaF6dlGKPp9TRzQ7HQT7WDRzExT0wfrQp34h.IaSCQswcW7.KREovJ0FV1muQBjjwqugnV8N7iiUNcyubavw09jvrUW1dd0_94ST1cUaxKhx._u3eTOkvpdpA77DvDl2vq8kKaRmleyOTnNHuv1nUun0KWKs3aEcGGhnhIE8d9mBb5micE.hGKTvWYn4QxlRakgnxX22Gky44TmnVSCPhNCyUevKUeoTtZ4vsTM.lVasYDx9gUPQk7gwQOVfy5d4obHg',};var a = document.createElement('script');a.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=9ea7d264ab7558fe';window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, location.href.length - window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;if (window.history && window.history.replaceState) {var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;history.replaceState(null, null,"\/wiki\/Level_40_stats_table?__cf_chl_rt_tk=CSSgKS7Sds.Zz21FtYfscHyBjufwaxAwgZh1KmyL5p4-1775887760-1.0.1.1-TvaPFYBwysG4fY2Kl9P9kip_hMqlypYZ87IH_Eez1XU"+ window._cf_chl_opt.cOgUHash);a.onload = function() {history.replaceState(null, null, ogU);}}document.getElementsByTagName('head')[0].appendChild(a);}());</script></body></html>

In [16]:
headers = {'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:149.0) Gecko/20100101 Firefox/149.0'}
heroes = httpx.get('https://feheroes.fandom.com/wiki/Level_40_stats_table', headers=headers)

In [17]:
heroes.encoding

'utf-8'

In [19]:
with open('lv40_heroes.html', 'w', encoding='utf-8') as file:
    file.write(heroes.text)